### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by Thor77** [reminiflux/reminiflux#1]
It would be nice to be able to control the interface using keyboard shortcuts (ideally the some ones Miniflux is using as well).

Probably not all of them are relevant to this interface, but going to the next/previous item using the keyboard would be great.

**Comment by a-bali** [comment]
Added some basic keyboard commands, press 'h' for details.

**Comment by Thor77** [comment]
Thanks! It looks like the algorithm for finding the next/previous feed is broken in some way (or at least not consistent with the display order), though: https://p.crapwa.re/selif/zvlg38ax.mp4

**Comment by a-bali** [comment]
Right, hopefully it is fixed now, please confirm.

**Comment by Thor77** [comment]
It's working correctly now, thanks!
